
name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm i

      - name: Build Implementations
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: "github.ref == 'refs/heads/main'"
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm i

      - name: Build Implementations
        run: npm run build

      - name: Clean Report
        run: npm run report:clean

      - name: Generate Implementations
        run: npm run report:generate

      - name: Evaluate Implementations
        run: npm run report:evaluate

      - name: Deploy Implementation Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data
